name: mlsc_uninstagram_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rive: ^0.9.0  # Fix the indentation here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Picsart_25-01-05_09-39-15-239.jpg
    - assets/login-teddy.riv
    - assets/Login.jpg
  
